version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_go_net

  postgress:
    image: postgres:latest
    container_name: 'postgress'
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
        - 5432:5432
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge